--- #YAML:1.0
name:               Digest-combined
version:            0.1
abstract:           Calculate multiple message digests simultaneously
author:
    - Ivan Shmakov <oneingray@gmail.com>
license:            public domain
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
